# fly.toml file generated for mi on 2022-09-03T12:49:12+08:00

app = "mi"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []



[build]
image = "grafana/grafana"


[mount]
source = "grafana_storage"
destination = "/var/lib/grafana"


[env]
# GF_INSTALL_PLUGINS = "grafana-worldmap-panel,grafana-clock-panel,grafana-synthetic-monitoring-app,hamedkarbasi93-kafka-datasource,blackcowmoo-googleanalytics-datasource,oci-metrics-datasource,grafana-github-datasource,grafana-sentry-datasource,grafana-x-ray-datasource,grafana-worldmap-panel,cloudflare-app"
GF_INSTALL_PLUGINS = "grafana-worldmap-panel,grafana-clock-panel,grafana-synthetic-monitoring-app,hamedkarbasi93-kafka-datasource,oci-metrics-datasource,grafana-github-datasource,grafana-sentry-datasource,grafana-x-ray-datasource,grafana-worldmap-panel,cloudflare-app"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
